# Generated by Django 4.2.11 on 2024-05-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='id')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('answer', models.TextField(verbose_name='ответ')),
            ],
        ),
    ]
