# Generated by Django 4.2.11 on 2024-05-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='id')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('options', models.TextField(verbose_name='Варианты Ответов')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('answer', models.TextField(verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
