# Generated by Django 4.2.11 on 2024-05-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
